on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@main
        - run: |
              curl -L https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2 | tar -xj --strip-components 1
              #clang++ -std=c++2a -O2 -march=native -fmodules-ts --precompile hyp2f1.cppm
              #clang++ -std=c++2a -O2 -march=native -fmodules-ts -fprebuilt-module-path=. hyp2f1.pcm main.cpp
              #./a.out
              git add 
              git config user.name 'Your Name'
              git config user.email 'you@example.com'
              git commit --allow-empty-message -m ''
              git push
