on: push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: |
            clang++ -std=c++2a -O2 -march=native -fmodules-ts --precompile hyp2f1.cppm
            clang++ -std=c++2a -O2 -march=native -fmodules-ts -fprebuilt-module-path=. hyp2f1.pcm main.cpp
            ./a.out
